version: '3'

services:
  pulse:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    environment: 
      HELLO_MESSAGE: It is hello msg from env
    volumes:
      - ./data:/app/data
